[package]
name = "miden-debug-engine"
description = "Core debugger engine for miden-debug"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true

[lib]
doctest = false

[features]
default = ["std"]
dap = ["std", "dep:miden-debug-dap", "dep:serde_json", "dep:socket2"]
std = [
    "dep:clap",
    "dep:glob",
    "dep:inventory",
    "dep:miden-assembly",
    "dep:miden-package-registry",
    "dep:miden-project",
    "dep:rustc-demangle",
    "dep:rustc-hash",
    "miden-assembly-syntax/std",
    "miden-core/std",
    "miden-debug-types/std",
    "miden-mast-package/std",
    "miden-processor/std",
    "num-traits/std",
    "serde/std",
    "thiserror/std",
    "toml/preserve_order",
]
proptest = ["std", "dep:proptest"]

[dependencies]
clap = { workspace = true, optional = true }
glob = { version = "0.3.1", optional = true }
inventory = { workspace = true, optional = true }
log.workspace = true
miden-assembly = { workspace = true, optional = true }
miden-assembly-syntax.workspace = true
miden-core.workspace = true
miden-debug-dap = { workspace = true, optional = true, features = ["client"] }
miden-debug-types.workspace = true
miden-mast-package.workspace = true
miden-package-registry = { workspace = true, optional = true }
miden-processor.workspace = true
miden-project = { workspace = true, optional = true }
num-traits = { version = "0.2", default-features = false }
proptest = { version = "1.4", optional = true }
rustc-demangle = { version = "0.1", optional = true, features = ["std"] }
rustc-hash = { workspace = true, optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
socket2 = { version = "0.6", optional = true }
smallvec = { version = "1.14", default-features = false, features = [
    "union",
    "const_generics",
    "const_new",
    "drain_filter",
] }
thiserror.workspace = true
toml = { version = "1.1.2", default-features = false, features = ["parse", "serde"] }

[dev-dependencies]
miden-assembly.workspace = true
tempfile = "3"
